"""Fix FK constraint on photo.room_id

Revision ID: b88aaad132a4
Revises: 0ac113b6a272
Create Date: 2025-07-27 23:31:01.869673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88aaad132a4'
down_revision = '0ac113b6a272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_photo_room_id', 'property', ['room_id'], ['id'])  # ✅ NAMED!

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
